version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '${FE_PORT}:5000'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=${HOST}:${BE_PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${BE_PORT}:3000'
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://db:27017/photoQuest
      - NODE_ENV=development

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  telegram-bot:
    build:
      context: ./telegram-bot-service
      dockerfile: Dockerfile
    volumes:
      - ./telegram-bot-service:/app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=mongodb://db:27017/photoQuest
      - NODE_ENV=development
    depends_on:
      - db

volumes:
  mongo-data:
