version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://db:27017/photoQuest
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  telegram-bot:
    build:
      context: ./telegram-bot-service
      dockerfile: Dockerfile
    volumes:
      - ./telegram-bot-service:/app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=mongodb://db:27017/photoQuest
      - NODE_ENV=production
    depends_on:
      - db

volumes:
  mongo-data:
